@@startuml Car is driving
loop car is driving
    Car -> ConnectedVehiclePlatform: Send waypoint
    ConnectedVehiclePlatform -> EventHub: Create event
end
loop read driving events
    ConnectedVehiclePlatform -> EventHub: Read events
    ConnectedVehiclePlatform -> CosmosDB: Store data
end
Car -> ConnectedVehiclePlatform: End Trip
ConnectedVehiclePlatform -> ServiceBus: TripEndeded
@@enduml