@@startuml Car is driving
loop car is driving
    Car -> RefArk.Car: Send waypoint
    RefArk.Car -> EventHub: Create event
end
loop read driving events
    RefArk.Car -> EventHub: Read events
    RefArk.Car -> CosmosDB: Store data
end
Car -> RefArk.Car: End Trip
RefArk.Car -> ServiceBus: Trip endeded [Topic:tripended]
RefArk.Car -> ServiceBus: Subscribe[Topic:tripended]
RefArk.Car -> RefArk.Car.DB: StoreTrip
RefArk.Customer -> ServiceBus: Subscribe[Topic:tripended]
RefArk.Customer -> RefArk.Customer.DB: UpdateCustomer
RefArk.Station -> ServiceBus: Subscribe[Topic:tripended]
RefArk.Station -> RefArk.Station.DB: StoreIncomingCar

@@enduml